name = "datatool-worker"
compatibility_date = "2025-02-06"
main = "src/worker.js"
site = { bucket = "./dist" }

[vars]
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0d2J6a2R2cGF0Y2N3cGJ5YWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NDMwOTcsImV4cCI6MjA1NzQxOTA5N30.9aNLnAqVlLmdUhd9Rd0D8B-tugik5vWwCdfwW-26oOU"
VITE_SUPABASE_URL = "https://vtwbzkdvpatccwpbyaja.supabase.co"
